#---------------------------------------------------
# Tanner Bernth
# Robert Walters
# Makefile
#---------------------------------------------------

make:
	javac Point.java
	javac GraphicView.java
	javac GUI.java
	javac Seqnbody.java